### ISSUE TITLE
Error importing nakamajs

### ISSUE THREAD

**Issue by tidianform** [heroiclabs/nakama-js#81]
There seems to be a bug in the packaging of the JS SDK
Moving from Rollup over to using esbuild might have created the bug

yarn add @heroiclabs/nakama-js
import * as nakamajs from "@heroiclabs/nakama-js";

```
error: Error: While trying to resolve module `@heroiclabs/nakama-js` from file `C:\Users\simtj\Desktop\NakamaClient\App.js`, the package `C:\Users\simtj\Desktop\NakamaClient\node_modules\@heroiclabs\nakama-js\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\simtj\Desktop\NakamaClient\node_modules\@heroiclabs\nakama-js\packages\nakama-js\dist\nakama-js.iife.js`. Indeed, none of these files exist:

  * C:\Users\simtj\Desktop\NakamaClient\node_modules\@heroiclabs\nakama-js\packages\nakama-js\dist\nakama-js.iife.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * C:\Users\simtj\Desktop\NakamaClient\node_modules\@heroiclabs\nakama-js\packages\nakama-js\dist\nakama-js.iife.js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

**Comment by abdulrashid1991** [comment]
Any updates on this issue

**Comment by lugehorsam** [comment]
@abdulrashid1991 we'll be fixing this early next week as we return from the holidays.

**Comment by lugehorsam** [comment]
@abdulrashid1991 @tidianform we've released a new version of the client on npm (2.1.2) that should resolve this issue.

**Comment by polats** [comment]
Hi all, we've run into a similar issue importing nakamajs after updating to 2.1.2-- reverting to 2.0.1 fixed the issue. Here's more info on the error: 

![image](https://user-images.githubusercontent.com/26343/103988233-aea09280-51c8-11eb-8a89-680ce6656c6c.png)

**Comment by lugehorsam** [comment]
Hey @polats, could you instead try `import {Client} from "@heroiclabs/nakama-js"`? I am going to update the documentation if there are no issues with that. I've tested this on the most recent release but not with your webpack setup.

**Comment by abdulrashid1991** [comment]
@lugehorsam I am also facing the same issue

![Screenshot_1](https://user-images.githubusercontent.com/8100924/104119723-767b8a00-5357-11eb-8a45-2e3c4e9a9f57.png)

**Comment by lugehorsam** [comment]
@polats @abdulrashid1991 could you take a look at this example project I committed to the repo? Perhaps there are differences in your Webpack setup from the minimal example there.  https://github.com/heroiclabs/nakama-js/tree/master/packages/nakama-js-webpack-example

**Comment by gauravadhikari1997** [comment]
I am also facing same issue @lugehorsam 

Project is running on Create-React-App template so the webpack is preconfigured and would not be an issue.

From the [documentation](https://github.com/facebook/create-react-app#get-started-immediately) :
> You don’t need to install or configure tools like Webpack or Babel. They are preconfigured and hidden so that you can focus on the code.

For your reference I am attaching my projects webpack.config.js file from node_modules/react-scripts/config
[webpack.config.zip](https://github.com/heroiclabs/nakama-js/files/5794418/webpack.config.zip)

Please look into the matter. Thanks

**Comment by polats** [comment]
Still the same issue with import {Client} @lugehorsam . There might be a clue with @gauravadhikari1997 's setup, I'm also not using webpack but am using react-app-rewired

**Comment by abdulrashid1991** [comment]
I tried the https://github.com/heroiclabs/nakama-js/tree/master/packages/nakama-js-webpack-example that also has the same issue 
![Screenshot_2](https://user-images.githubusercontent.com/8100924/104276123-40aae280-54ca-11eb-9a26-6e422f53eb3d.png)

**Comment by lugehorsam** [comment]
Thanks everyone for the help. I can reproduce both the CRA and Webpack issues (I wasn't seeing it initially due to my cache.) Aiming for a new release today. @polats @abdulrashid1991 @gauravadhikari1997

**Comment by lugehorsam** [comment]
Please try the latest release, 2.1.3: https://www.npmjs.com/package/@heroiclabs/nakama-js
